### ISSUE TITLE
Supplementary Figures

### ISSUE THREAD

**Issue by LTLA** [davismcc/scaterPaperExtras#29]
In the ecosystem figure, consider only mentioning packages, rather than methods in general, as the latter are not directly compatible unless they've been implemented somewhere.

Also, for figure 5, the "(PCA on QC metrics)" in parentheses is probably not required. There's an explanation in the screenshot, so why restate it in the caption?

**Comment by davismcc** [comment]
Yes, good point about the ecosystem figure. I've adjusted accordingly.

Yep, agreed on fig 5 too. Have adjusted that now.
