### ISSUE TITLE
Case Study

### ISSUE THREAD

**Issue by LTLA** [davismcc/scaterPaperExtras#30]
Table of contents is missing the 6. Also, don't bother hiding the code, it's annoying to have to click them open to see what the plot or output refers to.

---

> Technical stuff

Hmm. I'm sure we could be less casual about this.

---

> View the first few entris for the cell metadata:

Entries, presumably. Also consider using `head` instead.

---

I have no idea what the `plotReducedDim` calls after the first PCA outlier plot in Section 3 are showing.

---

No need for a table of cell cycle gene information, I'll take your word for it. If you must show me the cell cycle genes, just give me their names. No one's going to read the table anyway, it's too wide.

---

> It can also be useful to look at total expression levels acrsoo gene biotypes

Across?

---

> To the best of my knowledge...

Our? It's not the royal We.

---

Need to split up the normalization section into subsections, it's far too long to read without any breaks.

---

Probably don't need to test so many `k` with RUVSeq. And just stick with one of the RUV methods, once you know how to do one, the rest follow. We're not writing a tutorial for RUVSeq, remember. Besides, RUVg doesn't seem to work so well, so why bother mentioning it?

**Comment by davismcc** [comment]
Thanks for working all the way through this, Aaron. I've applied all of these changes and trimmed down a little more too.
