### ISSUE TITLE
Page 6: Software and data integration: Paragraph 1

### ISSUE THREAD

**Issue by LTLA** [davismcc/scaterPaperExtras#38]
> heterogeneous gene expression analyses (Lun et al., 2016; ...

That's news to me. I don't remember the paper having much to do with new methods for heterogeneous gene expression analyses.

**Comment by davismcc** [comment]
Good point. Added this since scran can do variance decomposition and this is the best(?) reference for scran, but I guess that's not an appropriate reference for that functionality. I'll take it out.
