### ISSUE TITLE
Supplementary Figures

### ISSUE THREAD

**Issue by LTLA** [davismcc/scaterPaperExtras#41]
Our affiliations don't match up to those in the main text. And speaking of which, it's probably best to throw in "CRUK Cambridge Institute, University of Cambridge, ...".

**Comment by davismcc** [comment]
Good catch. Forgot I dropped my Oxford Stats affiliation. (What did they ever do for me? Apart from award me a DPhil :P). Have fixed these and added "university of Cambridge" to CRUK.
