### ISSUE TITLE
Case Study

### ISSUE THREAD

**Issue by LTLA** [davismcc/scaterPaperExtras#42]
> ... more than one cell ( or cell debris from other cells ) are being sequenced...

are -> is.

---

To normalize using ERCC spike-ins, you need to use `computeSpikeFactors` after setting `isSpike`:

``` r
isSpike(scDataQC) <- "spikes"
scDataQC_spikenorm <- computeSpikeFactors(scDataQC)
```

The `get.spikes` argument in `computeSumFactors` only controls whether spike-in transcripts are filtered out in the deconvolution method, it doesn't switch over entirely to spike-in normalization.

---

Consider using `r Biocpkg("scater")` for package references, which links straight to the scater BioC page.

**Comment by davismcc** [comment]
Cool - thanks for the clarification on computeSpikeFactors.

I didn't know about `Biocpkg`, so thanks for the heads up!

These are fixed now.
