### ISSUE TITLE
Page 2: Implementation: Paragraph 1

### ISSUE THREAD

**Issue by LTLA** [davismcc/scaterPaperExtras#6]
> The package builds on many other R packages: ...

There is far too much stuff listed here. Just do:

> The package builds on many other R packages, including Biobase and BiocGenerics for core Bioconductor functionality (Huber et al. 2015); destiny (Angerer et al., 2015) and Rtsne (Krijthe, 2015) for dimensionality reduction; and edgeR (Robinson et al., 2010) and limma (Ritchie et al., 2015) for model fitting and statistical analyses. A full set of dependencies is provided in the Supplementary Materials.

This should cut down your references by a lot, probably.

**Comment by kieranrcampbell** [comment]
While I agree with Davis that it's good to cite packages used I agree that there are too many listed here. Might be worth citing Hadley Wickham once though since half the packages are his (e.g. plotting with ggplot2 [cite]).

**Comment by davismcc** [comment]
Yep, very sensible changes. I've switched this to Aaron's text plus a short sentence mentioning ggplot2 with a citation.
