### ISSUE TITLE
Page 3: SCESet: Paragraph 2

### ISSUE THREAD

**Issue by LTLA** [davismcc/scaterPaperExtras#8]
> Single-cell datasets are now incorporating more data modalities than just transcriptomic data; many of these (such as cell-level data such as FACS marker expression) can currently be captured in SCESet objects, and future development of the package will incorporate different types of assay data (such as targeted genotyping and epigenetic data) into the class.

This is a bit of a weird place to say the above. Some stuff can be moved to the previous paragraph (see #7), where you talk about storage. I don't see the point in talking about future development in this section - we're in the  Results so we should be talking about what we've got now.

**Comment by davismcc** [comment]
Yep, agreed. I applied the change from #7, so this is gone now.
