### ISSUE TITLE
Page 3: Data processing: Paragraph 1

### ISSUE THREAD

**Issue by LTLA** [davismcc/scaterPaperExtras#9]
> Once raw read data have been obtained, the expression level of genomic features such as transcripts or genes must be quantified.

This wording is a bit jolting as it implies some continuity from the previous section, which is not the case. Better to break the flow and say something like:

> An important initial step in scRNA-seq data processing is to quantify the expression level of genomic features such as transcripts or genes from the raw sequencing data.

---

> ... can be readily used in a scater workflow (Figure 1).

Put a bit of a link to the previous section and say something like:

> ... can be readily stored in a SCESet object and used in a scater workflow (Figure 1).

**Comment by davismcc** [comment]
Applied.
